language: python
python:
  - "3.6"
install: "pip install -r sigmapiweb/requirements/github.txt"
before_script: cd sigmapiweb
script: make quality
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master
