# Generated by Django 3.1.6 on 2021-10-05 20:36

import apps.Scholarship.models
import common.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrackedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_hours', models.IntegerField(validators=[apps.Scholarship.models.validate_number])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('scholarship_head', 'Can modify study hours.'),),
            },
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudyHoursRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_hours', models.IntegerField(validators=[apps.Scholarship.models.validate_number])),
                ('date', models.DateField(validators=[apps.Scholarship.models.validate_date])),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[apps.Scholarship.models.validate_stars])),
                ('text', models.CharField(max_length=1000)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('isbn_number', models.CharField(max_length=100)),
                ('course', models.CharField(blank=True, default='', max_length=10)),
                ('edition', models.CharField(max_length=100)),
                ('item_pdf', models.FileField(upload_to='protected/scholarship/library')),
                ('approved', models.BooleanField(default=False)),
                ('submittedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('professor', models.CharField(max_length=100)),
                ('catalog_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarship.course')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AcademicResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=1000)),
                ('course_number', models.CharField(max_length=100)),
                ('professor_name', models.CharField(max_length=100)),
                ('resource_pdf', models.FileField(upload_to='protected/scholarship/resources')),
                ('approved', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True)),
                ('term', models.CharField(blank=True, choices=[('A', 'A Term'), ('B', 'B Term'), ('C', 'C Term'), ('D', 'D Term'), ('E', 'E Term')], max_length=1)),
                ('submittedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
    ]
