# Generated by Django 3.1.6 on 2021-11-09 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='catalog_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Z]+[0-9]+')]),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='catalog_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarship.course', to_field='catalog_code'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='term',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('S', 'S'), ('F', 'F')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='year',
            field=models.CharField(max_length=2),
        ),
    ]
