# Generated by Django 3.1.6 on 2021-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='year',
            field=models.CharField(max_length=2),
        ),
    ]
