# Generated by Django 3.1.6 on 2021-11-11 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarship', '0002_auto_20211109_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
