# Generated by Django 3.1.6 on 2021-11-11 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarship', '0003_auto_20211111_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
