# Generated by Django 3.1.1 on 2020-10-22 20:34

import apps.Scholarship.models
import common.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scholarship', '0005_change_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseOfficeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.BooleanField(default=False)),
                ('facilitator', models.CharField(max_length=100)),
                ('day_and_time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[apps.Scholarship.models.validate_stars])),
                ('text', models.CharField(max_length=1000)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('professor', models.CharField(max_length=100)),
                ('catalog_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarship.course')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
    ]
