# Generated by Django 3.1.13 on 2022-02-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("UserInfo", "0010_auto_20201203_2032")]

    operations = [
        migrations.AddField(
            model_name="userinfo", name="linkedIn", field=models.TextField(blank=True)
        )
    ]
