# Generated by Django 3.1.13 on 2022-02-22 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0011_userinfo_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='linkedIn',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(regex='^\\w*$')]),
        ),
    ]
