# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliquegroup',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
