# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slack', '0002_auto_20190411_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliquegroup',
            name='members',
            field=models.ManyToManyField(to='Slack.CliqueUser'),
        ),
    ]
