# Generated by Django 3.1.13 on 2023-01-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyListV2', '0015_nonbinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='max_girl_party_invites',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='party',
            name='max_guy_party_invites',
            field=models.IntegerField(default=1),
        ),
    ]
