# Generated by Django 3.1.13 on 2023-01-29 21:51

from django.db import migrations

"""
Adding invite limits to the existing parties
"""


def add_invite_limits_to_existing_parties(apps, schema_editor):
    client = apps.get_model("PartyListV2", "party")
    for party in client.objects.all():
        party.max_guy_party_invites = 0
        party.max_girl_party_invites = 0
        party.save()


class Migration(migrations.Migration):
    dependencies = [
        ("PartyListV2", "0016_add_max_gendered_invites"),
    ]

    operations = [
        migrations.RunPython(
            add_invite_limits_to_existing_parties,
            reverse_code=migrations.RunPython.noop,
        )
    ]
