# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django CI

on:
  push:
    branches:
      - master
      - demo
  pull_request:
    branches:
      - master
      - demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Python 3.8 is the version we use on production.
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f sigmapiweb/requirements/github.txt ]; then pip install -r sigmapiweb/requirements/github.txt; fi
    - name: Run test cases
      run: |
        # Need to go into sigmapiweb/ directory for fixtures to be found correctly
        cd sigmapiweb && python3 manage.py test
